### ISSUE TITLE
Symlinking needs permissions?

### ISSUE THREAD

**Issue by mikedelgrosso** [rubyisbeautiful/multi-app#1]
```
TASK [rubyisbeautiful.multi-app : symlink if requested] *******************************************************************************************************************************
fatal: [server.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error while linking: [Errno 13] Permission denied", "path": "/apps/java/latest", "state": "absent"}
```

https://github.com/rubyisbeautiful/multi-app/blob/e556c97866be684e1795870989667b98587ce2cc/tasks/install_each.yml#L93

Is this task missing a `become: "{{ multiapp_become }}"`?

**Comment by rubyisbeautiful** [comment]
Looking

**Comment by rubyisbeautiful** [comment]
Can you give me more info?  I don't even remember anything.  Also OS... CentOS/RHEL 6 or 7?  What is the `--become-user` it is running as?  Is it running with `become`?  I can't reproduce yet.  If I run w/o become, it fails creating the root dir.  If I run with become, it doesn't fail for me.  Thanks

**Comment by mikedelgrosso** [comment]
RHEL7 -- You are correct, play works when running as become. Mostly confusion on my part when using the role. Otherwise, all good.  Thx
